### ISSUE TITLE
Dockerfile.linux build fails

### ISSUE THREAD

**Issue by ahasikos** [sandbox-quantum/sandwich#10]
Docker build of Dockerfile.linux fails with the attached output.

## Steps to reproduce
`docker build --pull --rm -f "Dockerfile.linux" -t sandwich:latest "."`

## Output
[Docker_build_error_output.txt](https://github.com/sandbox-quantum/sandwich/files/12512365/Docker_build_error_output.txt)

**Comment by eduser25** [comment]
Hey @ahasikos , it seems your container is failing to download boringssl from the official boringssl repo, or maybe is taking too much time before java gives up (https://github.com/open-quantum-safe/boringssl/archive/e2d2587065eacfe97aaae940dd43cd964b71f5b4.tar.gz precisely)

Can you double check you can download on the host?

```
Error downloading [https://github.com/open-quantum-safe/boringssl/archive/e2d2587065eacfe97aaae940dd43cd964b71f5b4.tar.gz] to /home/user/.cache/bazel/_bazel_user/5b894d12f288a1c11d59cee251fbf4c9/external/open-quantum-safe.boringssl/temp13775332165000890948/e2d2587065eacfe97aaae940dd43cd964b71f5b4.tar.gz: java.net.SocketTimeoutException: Read timed out
```

**Comment by ahasikos** [comment]
@eduser25 after re-trying it seems to work. Thanks for looking into it
