### ISSUE TITLE
Build for C API fails on Ubuntu 22.04.3 LTS

### ISSUE THREAD

**Issue by ahasikos** [sandbox-quantum/sandwich#9]
## Description
I am trying to build the library using the instructions [here](https://sandbox-quantum.github.io/sandwich/install.html) but I seem to get the following error:

```
INFO: Analyzed target //:export (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/alex/.cache/bazel/_bazel_alex/dffc9a5f3a5f7240922e017d89949fe5/external/bartleby-llvm-project/llvm/BUILD.bazel:136:11: Compiling llvm/lib/Demangle/DLangDemangle.cpp [for tool] failed: (Exit 1): clang failed: error executing command (from target @bartleby-llvm-project//llvm:Demangle) /usr/lib/llvm-13/bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer -g0 ... (remaining 68 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from external/bartleby-llvm-project/llvm/lib/Demangle/DLangDemangle.cpp:16:
external/bartleby-llvm-project/llvm/include/llvm/Demangle/Demangle.h:12:10: fatal error: 'cstddef' file not found
#include <cstddef>
         ^~~~~~~~~
1 error generated.
Target //:export failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.574s, Critical Path: 1.24s
INFO: 99 processes: 94 internal, 5 linux-sandbox.
FAILED: Build did NOT complete successfully
```

## Environment
Output of my os-release:
`PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian`

## Steps to reproduce

1. Install Ubuntu 22.04.03
2. Follow instructions as of [here](https://sandbox-quantum.github.io/sandwich/install.html)

**Comment by eduser25** [comment]
hey @ahasikos , thanks for posting.

Can you check if you have `libstdc++-XX-dev` installed? (being XX version revision available in your distro)

Alternatively also, just use the[ dockerfile on linux](https://github.com/sandbox-quantum/sandwich/blob/main/Dockerfile.linux) to build

**Comment by ahasikos** [comment]
Hi @eduser25, i haven't explored more into it but dockerfile on linux works just fine.
